language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -q -r requirements-dev.txt codecov
# command to run tests
script:
  - flake8 blackjack
  - python -m doctest README.md
  - pytest --cov=blackjack

after_success:
  - codecov